### ISSUE TITLE
MOBILE gCrit case study: down to the wire page divider 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#359] opened 2018-02-08 16:01 UTC
<img width="408" alt="screen shot 2018-02-08 at 11 00 22 am" src="https://user-images.githubusercontent.com/31738798/35983076-47136fee-0cbf-11e8-8611-40340a2f9e03.png">

Is there a way to adapt the design so that the images could be more legible on mobile?

**Comment by ekfuhrmann** [comment] 2018-02-12 18:28
Duplicate of #350

**Closed by ekfuhrmann** 2018-02-12 18:28 UTC
Labels: Case Study, Mobile, dev, gCrit
